local Addon = select(2, ...)

local FAQ = {}
Addon.FAQ = FAQ

FAQ.Header = "FAQ/Help"

FAQ.Points = {
    ["1. What is the purpose of the addon?"] = "The addon provides several ways to view reputation changes for each faction. It is designed to allow the greatest flexibility in how and where to display these changes, yet the addon works out-of-the-box.",
    ["2. What options does the addon provide?"] = "The main functionality is to configure the reputation change message using Tags. These are chunks of text displaying various aspects about the reputation change that has just taken place. These include things like faction name, current change, faction standing, and so on. This message can then be displayed in the UI in several ways.\n Another option is to have on-screen bars that capture recent reputation changes. While these bars have standardized text, you can change their appearance or the length of time they are displayed on the screen.\n The addon also displays a tooltip next to the minimap icon with the reputation changes in the current session.",
    ["3. How do I create a reputation change message?"] = "The message can be created in the 'Message' panel in the 'pattern' field. To compose it, use the Tags. Each of them shows a different element of the reputation that has just been changed. Tags must be enclosed in square brackets '[]' and are case sensitive.\n For example, the Tag 'name' entered in the 'pattern' section as '[name]' translates to the text 'Stormwind' when the reputation is changed (for Stormwind, of course).\n If you want some static text to be displayed in addition to the generated text from Tags, then write it out as it should be displayed. For example, if you want 'Faction Stormwind [Honored]' to be displayed, you will type 'Faction [name] [[standing]]' in the 'pattern' field. As you can see with the 'standing' tag, it is enclosed (as requested) in square brackets, but then the second outer enclosed square brackets are displayed as text in the resulting message.\n Don't forget to press the 'Accept' button after changing the 'pattern' field.",
    ["4. What does 'c_' in the Tag name mean?"] = "Some Tags have the option to display in the color of the current faction standing. Colors can be defined in the 'Colors' panel, where there are several presets to choose from, or you can define the colors yourself.\n For example, the Tag 'standing' will be displayed as 'Honored' in white (if standing is honored, of course). However, if you use the Tag 'c_standing', then the text 'Honored' will be displayed in the color of the standing honored as defined on the “Colors” panel. Or using the 'c_name' Tag, the faction name (for example, 'Stormwind') will be displayed in the color of the standing.",
    ["5. What does 'Short' in the name tag mean?"] = "Some tags' text representation may be unnecessarily long. Therefore, there is an option to shorten the length of their display to save space in the message and fit them on one line.\n A typical example is the faction standing. The standard Tag 'standing' will display the text 'Honored', 'Renown 25' or 'True Friend,' for example. The 'standingShort' tag will then only show 'H,' 'R25' or 'TF.' The number of initial letters of every word of Tags with the suffix 'Short' can be set in the 'Tag options' panel in the '...Short' section.",
    ["6. Setting Tags with Additional Options"] = "Some tags have additional options for display, which can be set in the 'Tag options' panel. Each of these tags has its own section.\n For example, for the tag 'bar,' you can choose the characters that will form the bar and how many of them there should be. For the tag 'barTexture,' you can choose the texture or size of the bar.",
    ["7. Conditional Tag Text"] = "Sometimes we would like to display additional text to a tag, but only if the tag is displayed. In that case, the format of the tag changes to '[{prefix}tag{suffix}],' where both {prefix} and {suffix} are optional.\n If '[tag]' (without prefixes and suffixes) evaluates to an empty value, neither the prefix nor the suffix will be displayed.\n There cannot be any spaces except inside the prefix or suffix, which can be any text, even with spaces (or only spaces if you wish).\n For example, the pattern '[{Renown level: }renownLevel]' will display the message 'Renown level: 25,' but only if the tag [renownLevel] displays '25'. If it is empty, then the whole tag will not display in the resulting message at all. The pattern '[{Level }paragonLevel{ paragon}]' will result in 'Level 5 paragon' with a similar condition.",
    ["8. Selecting the Output for a Reputation Change Message"] = "By default, when a reputation change occurs, the addon will display a message in the default chat tab. However, it also provides options to display the message in other ways. This can be set in the 'Output' panel. In addition to selecting an output, you can always display the message in chat and choose which chat windows to display the message in.\n There are several other outputs available, such as floating combat text. Some addons may add additional output options, such as MikBattleScrollText or Prat.",
    ["9. Displaying Reputation Bars on the Screen"] = "The addon provides a feature to display reputation bars on the screen for factions whose reputation has changed within a certain time period. This feature can be accessed through the 'Reputation bars' panel, where you can choose whether and how you want the bars to be displayed, as well as set the time period in seconds during which the bars will be shown from the last reputation change corresponding to each bar. Setting this time to 0 will display the bars for the entire session. If you want to hide a bar manually, you can simply right-click on it.",
    ["10. 'Splash' Reputations"] = "Sometimes, Blizzard may change some reputations internally without notifying the user. The addon has an option to catch these instances and report them.\n Enabling this option may slightly slow down the game, but it can be useful for keeping track of reputation changes.",
    ["11. How to test you settings?"] = "You can test your settings using the 'TEST' button positioned above the option panels. Here, you can choose the faction and the amount of change to test how your settings will be displayed in the actual game.",
}