local Addon = select(2, ...)

local FAQ = {}
Addon.FAQ = FAQ

FAQ.Header = "FAQ / Help"

FAQ.Points = {
    ["1. What is the purpose of the addon?"] = "The addon provides several ways to view reputation changes for each faction. It is designed to offer maximum flexibility in how and where these changes are displayed, while still working out-of-the-box with no setup required.",
    ["2. What options does the addon provide?"] = "The main feature is the ability to configure reputation change messages using Tags. Tags represent different aspects of a reputation change, such as the faction name, the amount gained, or the standing level. These messages can then be shown in multiple ways in the UI.\nAnother feature is on-screen bars that track recent reputation changes. While the bar text is standardized, you can customize their appearance and how long they remain visible.\nAdditionally, the addon provides a tooltip that appears when you hover over the minimap icon showing reputation changes during the current session.",
    ["3. How do I create a reputation change message?"] = "Messages are configured in the 'Message' panel in the 'pattern' field. You compose them using Tags, which must be enclosed in square brackets '[]' and are case sensitive.\nFor example, entering '[name]' in the pattern will show 'Stormwind' when your Stormwind reputation changes.\nYou can also add static text. For instance, typing 'Faction [name] [[standing]]' could display 'Faction Stormwind [Honored]'. The double brackets around '[standing]' display literal square brackets in the final message.\nDon't forget to press the 'Accept' button after editing the pattern.",
    ["4. What does 'c_' in a Tag mean?"] = "Some Tags support color formatting based on the faction's standing. Colors can be configured in the 'Colors' panel using presets or custom values.\nFor example, '[standing]' will display 'Honored' in plain white, while '[c_standing]' will display 'Honored' in the standing color you defined. Similarly, '[c_name]' will display the faction name ('Stormwind') in the standing color.",
    ["5. What does 'Short' in a Tag mean?"] = "Some Tag values can be long, so 'Short' variants are available for more compact display.\nFor example, '[standing]' might show 'Honored', 'Renown 25', or 'True Friend'. Meanwhile, '[standingShort]' could show 'H', 'R25', or 'TF'. The number of initial characters of each word used can be configured in the 'Tag Options' panel.",
    ["6. Tags with Additional Options"] = "Some Tags include extra customization options, available in the 'Tag options' panel.\nFor example, for '[bar]', you can define which characters make up the bar and how many to use. For '[barTexture]', you can choose the texture and size.",
    ["7. Conditional Tag Text"] = "You can attach optional text before or after a Tag, but only if the Tag itself displays something. The format is '[{prefix}tag{suffix}]'.\nIf '[tag]' resolves to empty, the prefix and suffix are not shown either.\nPrefix and suffix can contain any text (including spaces).\nExample: '[{Renown level: }renownLevel]' will display 'Renown level: 25' only if [renownLevel] has a value. Similarly, '[{Level }paragonLevel{ paragon}]' will show 'Level 5 paragon'.",
    ["8. Selecting the Output for Reputation Messages"] = "By default, reputation messages appear in the main chat frame. The 'Output' panel lets you choose other display methods. You can still keep chat output enabled and even choose which chat windows it appears in.\nOther outputs include floating combat text or support for addons like MikScrollingBattleText or Prat.",
    ["9. Displaying Reputation Bars"] = "Reputation bars can appear on-screen for recently changed factions. This is managed in the 'Reputation bars' panel. You can configure whether and how the bars are shown, as well as the duration (in seconds) they remain visible after a change. A value of 0 means the bar persists for the whole session. To hide a bar manually, simply right-click it.",
    ["10. 'Splash' Reputations"] = "Sometimes Blizzard internally adjusts reputations without showing a notification. The addon can detect and display these 'hidden' updates.\nThis option will moderately impact performance, but it ensures you never miss a change.",
    ["11. How do I test my settings?"] = "Use the 'TEST' button above the options panels. You can pick a faction and specify an amount of change to preview how your settings will look in-game.",
}
FAQ.Footer = "If you have further questions or need assistance, please visit the addon's page on CurseForge or GitHub to reach out."